image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME

before_script:
  - echo "CI_REGISTRY=$CI_REGISTRY"
  - echo "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE"
  - echo "CONTAINER_IMAGE=$CONTAINER_IMAGE"
  - echo "CI_PROJECT_URL=$CI_PROJECT_URL"

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

